### ISSUE TITLE
About TA-STS-ConvNet

### ISSUE THREAD

**Issue by CageChen** [LianghuiGuo/TS-SEFFNet#1]
Hi, I read your new paper "Triple-Attention-based Spatio-Temporal-Spectral Convolutional Network for Epileptic Seizure Prediction", but I can't find the repo at https://github.com/LianghuiGuo/TA-STS-ConvNet, is the code not ready yet?

**Comment by LianghuiGuo** [comment]
> 

Really sorry about this! These days being busy in recruit. I will publish code and notice you as soon as possible.

> Hi, I read your new paper "Triple-Attention-based Spatio-Temporal-Spectral Convolutional Network for Epileptic Seizure Prediction", but I can't find the repo at https://github.com/LianghuiGuo/TA-STS-ConvNet, is the code not ready yet?

**Comment by LianghuiGuo** [comment]
> Hi, I read your new paper "Triple-Attention-based Spatio-Temporal-Spectral Convolutional Network for Epileptic Seizure Prediction", but I can't find the repo at https://github.com/LianghuiGuo/TA-STS-ConvNet, is the code not ready yet?

Hi~, code is now ready in https://github.com/LianghuiGuo/TA-STS-ConvNet. Thank you for asking.

**Comment by CageChen** [comment]
Thanks~
